# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I:\RadPy\src\radpy\plugins\BeamAnalysis\view\BDMLDialog.ui'
#
# Created: Fri Jun 25 18:39:41 2010
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(797, 431)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(400, 370, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(6, 9, 771, 331))
        self.tabWidget.setObjectName("tabWidget")
        self.BeamDetails = QtGui.QWidget()
        self.BeamDetails.setObjectName("BeamDetails")
        self.layoutWidget = QtGui.QWidget(self.BeamDetails)
        self.layoutWidget.setGeometry(QtCore.QRect(520, 10, 212, 225))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.crossplaneNegativeJawLabel_4 = QtGui.QLabel(self.layoutWidget)
        self.crossplaneNegativeJawLabel_4.setObjectName("crossplaneNegativeJawLabel_4")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.crossplaneNegativeJawLabel_4)
        self.inplaneNegativeJawLineEdit_2 = QtGui.QLineEdit(self.layoutWidget)
        self.inplaneNegativeJawLineEdit_2.setObjectName("inplaneNegativeJawLineEdit_2")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.inplaneNegativeJawLineEdit_2)
        self.crossplanePositiveJawLabel_4 = QtGui.QLabel(self.layoutWidget)
        self.crossplanePositiveJawLabel_4.setObjectName("crossplanePositiveJawLabel_4")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.crossplanePositiveJawLabel_4)
        self.inplanePositiveJawLineEdit_2 = QtGui.QLineEdit(self.layoutWidget)
        self.inplanePositiveJawLineEdit_2.setObjectName("inplanePositiveJawLineEdit_2")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.inplanePositiveJawLineEdit_2)
        self.vendorLabel = QtGui.QLabel(self.layoutWidget)
        self.vendorLabel.setObjectName("vendorLabel")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.vendorLabel)
        self.vendorLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.vendorLineEdit.setObjectName("vendorLineEdit")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.vendorLineEdit)
        self.modelLabel = QtGui.QLabel(self.layoutWidget)
        self.modelLabel.setObjectName("modelLabel")
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.modelLabel)
        self.modelLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.modelLineEdit.setObjectName("modelLineEdit")
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.modelLineEdit)
        self.serialNumberLabel = QtGui.QLabel(self.layoutWidget)
        self.serialNumberLabel.setObjectName("serialNumberLabel")
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.serialNumberLabel)
        self.serialNumberLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.serialNumberLineEdit.setObjectName("serialNumberLineEdit")
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.serialNumberLineEdit)
        self.machineScaleLabel = QtGui.QLabel(self.layoutWidget)
        self.machineScaleLabel.setObjectName("machineScaleLabel")
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.LabelRole, self.machineScaleLabel)
        self.machineScaleComboBox = QtGui.QComboBox(self.layoutWidget)
        self.machineScaleComboBox.setObjectName("machineScaleComboBox")
        self.machineScaleComboBox.addItem(QtCore.QString())
        self.machineScaleComboBox.addItem(QtCore.QString())
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.FieldRole, self.machineScaleComboBox)
        self.gridLayout_4.addLayout(self.formLayout_5, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.layoutWidget_2 = QtGui.QWidget(self.BeamDetails)
        self.layoutWidget_2.setGeometry(QtCore.QRect(270, 10, 210, 233))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.crossplaneNegativeJawLabel = QtGui.QLabel(self.layoutWidget_2)
        self.crossplaneNegativeJawLabel.setObjectName("crossplaneNegativeJawLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.crossplaneNegativeJawLabel)
        self.crossplaneNegativeJawLineEdit = QtGui.QLineEdit(self.layoutWidget_2)
        self.crossplaneNegativeJawLineEdit.setObjectName("crossplaneNegativeJawLineEdit")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.crossplaneNegativeJawLineEdit)
        self.crossplanePositiveJawLabel = QtGui.QLabel(self.layoutWidget_2)
        self.crossplanePositiveJawLabel.setObjectName("crossplanePositiveJawLabel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.crossplanePositiveJawLabel)
        self.crossplanePositiveJawLineEdit = QtGui.QLineEdit(self.layoutWidget_2)
        self.crossplanePositiveJawLineEdit.setObjectName("crossplanePositiveJawLineEdit")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.crossplanePositiveJawLineEdit)
        self.gridLayout.addLayout(self.formLayout_2, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.inplaneJawPositionsLabel = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.inplaneJawPositionsLabel.setFont(font)
        self.inplaneJawPositionsLabel.setObjectName("inplaneJawPositionsLabel")
        self.gridLayout_2.addWidget(self.inplaneJawPositionsLabel, 0, 0, 1, 1)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.crossplaneNegativeJawLabel_2 = QtGui.QLabel(self.layoutWidget_2)
        self.crossplaneNegativeJawLabel_2.setObjectName("crossplaneNegativeJawLabel_2")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.crossplaneNegativeJawLabel_2)
        self.inplaneNegativeJawLineEdit = QtGui.QLineEdit(self.layoutWidget_2)
        self.inplaneNegativeJawLineEdit.setObjectName("inplaneNegativeJawLineEdit")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.inplaneNegativeJawLineEdit)
        self.crossplanePositiveJawLabel_2 = QtGui.QLabel(self.layoutWidget_2)
        self.crossplanePositiveJawLabel_2.setObjectName("crossplanePositiveJawLabel_2")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.crossplanePositiveJawLabel_2)
        self.inplanePositiveJawLineEdit = QtGui.QLineEdit(self.layoutWidget_2)
        self.inplanePositiveJawLineEdit.setObjectName("inplanePositiveJawLineEdit")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.inplanePositiveJawLineEdit)
        self.gridLayout_2.addLayout(self.formLayout_3, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.wedgeLabel = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.wedgeLabel.setFont(font)
        self.wedgeLabel.setObjectName("wedgeLabel")
        self.gridLayout_3.addWidget(self.wedgeLabel, 0, 0, 1, 1)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.crossplaneNegativeJawLabel_3 = QtGui.QLabel(self.layoutWidget_2)
        self.crossplaneNegativeJawLabel_3.setObjectName("crossplaneNegativeJawLabel_3")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.crossplaneNegativeJawLabel_3)
        self.crossplanePositiveJawLabel_3 = QtGui.QLabel(self.layoutWidget_2)
        self.crossplanePositiveJawLabel_3.setObjectName("crossplanePositiveJawLabel_3")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.crossplanePositiveJawLabel_3)
        self.wedgeTypeComboBox = QtGui.QComboBox(self.layoutWidget_2)
        self.wedgeTypeComboBox.setObjectName("wedgeTypeComboBox")
        self.wedgeTypeComboBox.addItem(QtCore.QString())
        self.wedgeTypeComboBox.addItem(QtCore.QString())
        self.wedgeTypeComboBox.addItem(QtCore.QString())
        self.wedgeTypeComboBox.addItem(QtCore.QString())
        self.wedgeTypeComboBox.addItem(QtCore.QString())
        self.wedgeTypeComboBox.addItem(QtCore.QString())
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.wedgeTypeComboBox)
        self.wedgeAngleLineEdit = QtGui.QLineEdit(self.layoutWidget_2)
        self.wedgeAngleLineEdit.setObjectName("wedgeAngleLineEdit")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.wedgeAngleLineEdit)
        self.gridLayout_3.addLayout(self.formLayout_4, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.layoutWidget_3 = QtGui.QWidget(self.BeamDetails)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 10, 220, 229))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Energylabel = QtGui.QLabel(self.layoutWidget_3)
        self.Energylabel.setObjectName("Energylabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.Energylabel)
        self.EnergyLineEdit = QtGui.QLineEdit(self.layoutWidget_3)
        self.EnergyLineEdit.setObjectName("EnergyLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.EnergyLineEdit)
        self.particleLabel = QtGui.QLabel(self.layoutWidget_3)
        self.particleLabel.setObjectName("particleLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.particleLabel)
        self.particleComboBox = QtGui.QComboBox(self.layoutWidget_3)
        self.particleComboBox.setObjectName("particleComboBox")
        self.particleComboBox.addItem(QtCore.QString())
        self.particleComboBox.addItem(QtCore.QString())
        self.particleComboBox.addItem(QtCore.QString())
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.particleComboBox)
        self.SADLabel = QtGui.QLabel(self.layoutWidget_3)
        self.SADLabel.setObjectName("SADLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.SADLabel)
        self.SADLineEdit = QtGui.QLineEdit(self.layoutWidget_3)
        self.SADLineEdit.setObjectName("SADLineEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.SADLineEdit)
        self.SSDLabel = QtGui.QLabel(self.layoutWidget_3)
        self.SSDLabel.setObjectName("SSDLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.SSDLabel)
        self.SSDLineEdit = QtGui.QLineEdit(self.layoutWidget_3)
        self.SSDLineEdit.setObjectName("SSDLineEdit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.SSDLineEdit)
        self.collimatorAngleLabel = QtGui.QLabel(self.layoutWidget_3)
        self.collimatorAngleLabel.setObjectName("collimatorAngleLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.collimatorAngleLabel)
        self.collimatorAngleLineEdit = QtGui.QLineEdit(self.layoutWidget_3)
        self.collimatorAngleLineEdit.setObjectName("collimatorAngleLineEdit")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.collimatorAngleLineEdit)
        self.gantryAngleLabel = QtGui.QLabel(self.layoutWidget_3)
        self.gantryAngleLabel.setObjectName("gantryAngleLabel")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.gantryAngleLabel)
        self.gantryAngleLineEdit = QtGui.QLineEdit(self.layoutWidget_3)
        self.gantryAngleLineEdit.setObjectName("gantryAngleLineEdit")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.gantryAngleLineEdit)
        self.applicatorLabel = QtGui.QLabel(self.layoutWidget_3)
        self.applicatorLabel.setObjectName("applicatorLabel")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.applicatorLabel)
        self.applicatorLineEdit = QtGui.QLineEdit(self.layoutWidget_3)
        self.applicatorLineEdit.setObjectName("applicatorLineEdit")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.applicatorLineEdit)
        self.accessorYLabel = QtGui.QLabel(self.layoutWidget_3)
        self.accessorYLabel.setObjectName("accessorYLabel")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.accessorYLabel)
        self.accessorYLineEdit = QtGui.QLineEdit(self.layoutWidget_3)
        self.accessorYLineEdit.setObjectName("accessorYLineEdit")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.accessorYLineEdit)
        self.gridLayout_5.addLayout(self.formLayout, 1, 0, 1, 1)
        self.tabWidget.addTab(self.BeamDetails, "")
        self.MeasurementDetails = QtGui.QWidget()
        self.MeasurementDetails.setObjectName("MeasurementDetails")
        self.tabWidget.addTab(self.MeasurementDetails, "")
        self.Data = QtGui.QWidget()
        self.Data.setObjectName("Data")
        self.tabWidget.addTab(self.Data, "")
        self.vendorLabel.setBuddy(self.vendorLineEdit)
        self.modelLabel.setBuddy(self.modelLineEdit)
        self.serialNumberLabel.setBuddy(self.serialNumberLineEdit)
        self.Energylabel.setBuddy(self.EnergyLineEdit)
        self.particleLabel.setBuddy(self.particleComboBox)
        self.SADLabel.setBuddy(self.SADLineEdit)
        self.SSDLabel.setBuddy(self.SSDLineEdit)
        self.collimatorAngleLabel.setBuddy(self.collimatorAngleLineEdit)
        self.gantryAngleLabel.setBuddy(self.gantryAngleLineEdit)
        self.applicatorLabel.setBuddy(self.applicatorLineEdit)
        self.accessorYLabel.setBuddy(self.accessorYLineEdit)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Radiation Device", None, QtGui.QApplication.UnicodeUTF8))
        self.crossplaneNegativeJawLabel_4.setText(QtGui.QApplication.translate("Dialog", "Negative Jaw", None, QtGui.QApplication.UnicodeUTF8))
        self.crossplanePositiveJawLabel_4.setText(QtGui.QApplication.translate("Dialog", "Positive Jaw", None, QtGui.QApplication.UnicodeUTF8))
        self.vendorLabel.setText(QtGui.QApplication.translate("Dialog", "&Vendor", None, QtGui.QApplication.UnicodeUTF8))
        self.modelLabel.setText(QtGui.QApplication.translate("Dialog", "&Model", None, QtGui.QApplication.UnicodeUTF8))
        self.serialNumberLabel.setText(QtGui.QApplication.translate("Dialog", "Serial &Number", None, QtGui.QApplication.UnicodeUTF8))
        self.machineScaleLabel.setText(QtGui.QApplication.translate("Dialog", "Machine Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.machineScaleComboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "IEC 1217", None, QtGui.QApplication.UnicodeUTF8))
        self.machineScaleComboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "Varian IEC", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Crossplane Jaw Positions", None, QtGui.QApplication.UnicodeUTF8))
        self.crossplaneNegativeJawLabel.setText(QtGui.QApplication.translate("Dialog", "Negative Jaw", None, QtGui.QApplication.UnicodeUTF8))
        self.crossplanePositiveJawLabel.setText(QtGui.QApplication.translate("Dialog", "Positive Jaw", None, QtGui.QApplication.UnicodeUTF8))
        self.inplaneJawPositionsLabel.setText(QtGui.QApplication.translate("Dialog", "Inplane Jaw Positions", None, QtGui.QApplication.UnicodeUTF8))
        self.crossplaneNegativeJawLabel_2.setText(QtGui.QApplication.translate("Dialog", "Negative Jaw", None, QtGui.QApplication.UnicodeUTF8))
        self.crossplanePositiveJawLabel_2.setText(QtGui.QApplication.translate("Dialog", "Positive Jaw", None, QtGui.QApplication.UnicodeUTF8))
        self.wedgeLabel.setText(QtGui.QApplication.translate("Dialog", "Wedge", None, QtGui.QApplication.UnicodeUTF8))
        self.crossplaneNegativeJawLabel_3.setText(QtGui.QApplication.translate("Dialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.crossplanePositiveJawLabel_3.setText(QtGui.QApplication.translate("Dialog", "Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.wedgeTypeComboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "No_Wedge", None, QtGui.QApplication.UnicodeUTF8))
        self.wedgeTypeComboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "Hard_Wedge", None, QtGui.QApplication.UnicodeUTF8))
        self.wedgeTypeComboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "Dynamic_Wedge", None, QtGui.QApplication.UnicodeUTF8))
        self.wedgeTypeComboBox.setItemText(3, QtGui.QApplication.translate("Dialog", "Virtual_Wedge", None, QtGui.QApplication.UnicodeUTF8))
        self.wedgeTypeComboBox.setItemText(4, QtGui.QApplication.translate("Dialog", "Enhanced_Wedge", None, QtGui.QApplication.UnicodeUTF8))
        self.wedgeTypeComboBox.setItemText(5, QtGui.QApplication.translate("Dialog", "Soft_Wedge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Beam Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.Energylabel.setText(QtGui.QApplication.translate("Dialog", "&Energy (MeV)", None, QtGui.QApplication.UnicodeUTF8))
        self.particleLabel.setText(QtGui.QApplication.translate("Dialog", "&Particle", None, QtGui.QApplication.UnicodeUTF8))
        self.particleComboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "Photon", None, QtGui.QApplication.UnicodeUTF8))
        self.particleComboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "Electron", None, QtGui.QApplication.UnicodeUTF8))
        self.particleComboBox.setItemText(2, QtGui.QApplication.translate("Dialog", "Proton", None, QtGui.QApplication.UnicodeUTF8))
        self.SADLabel.setText(QtGui.QApplication.translate("Dialog", "S&AD (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.SSDLabel.setText(QtGui.QApplication.translate("Dialog", "&SSD (mm)", None, QtGui.QApplication.UnicodeUTF8))
        self.collimatorAngleLabel.setText(QtGui.QApplication.translate("Dialog", "&Collimator Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.gantryAngleLabel.setText(QtGui.QApplication.translate("Dialog", "&Gantry Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.applicatorLabel.setText(QtGui.QApplication.translate("Dialog", "&Applicator", None, QtGui.QApplication.UnicodeUTF8))
        self.accessorYLabel.setText(QtGui.QApplication.translate("Dialog", "Accessor&y", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.BeamDetails), QtGui.QApplication.translate("Dialog", "Beam Details", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MeasurementDetails), QtGui.QApplication.translate("Dialog", "Measurement Details", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Data), QtGui.QApplication.translate("Dialog", "Data", None, QtGui.QApplication.UnicodeUTF8))

